# Generated by Django 3.1.7 on 2021-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210212_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('descrip', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
